FROM bitnami/spark:3.3.1

USER root

# copy Spark JARs
COPY ./src/spark/jars/spark-redis_2.12-3.1.0-SNAPSHOT-jar-with-dependencies.jar /opt/bitnami/spark/jars
COPY ./src/spark/jars/spark-avro_2.12-3.3.1.jar /opt/bitnami/spark/jars

# install any python dependencies
COPY ./requirements.txt /
RUN pip install -r /requirements.txt